### ISSUE TITLE
Dev dependencies included in published package

### ISSUE THREAD

**Issue by juanpmarin** [CosmicMind/materialcss#1]
Hi! 
It seems that dev dependencies are being downloaded when I install the package, these are the listed dependencies in npm:
![image](https://github.com/CosmicMind/materialcss/assets/13415603/b0f30e6c-a4bb-4b99-b058-5499e07fb921)

**Comment by daniel-jonathan** [comment]
Thank you for submitting this. Yes, this needs to be cleaned up. I'll publish a fix for this.

**Comment by daniel-jonathan** [comment]
@juanpmarin A new RC has been pushed. Thank you for bringing this to our attention. 

Since we are in RC mode, the documentation is quite light. Please feel free to create any discussions. 

As well, we are moving some files around and making it more flexible to develop new components, so bare with us if there are any breaking changes, we will do our best to make sure there are not any.

**Comment by juanpmarin** [comment]
@daniel-jonathan thanks a lot! great work with materialcss
I also noticed that themes are not being shipped with the package. Only the component scss are being shipped


![image](https://github.com/CosmicMind/materialcss/assets/13415603/923faac7-6277-4fda-9fdb-d9907f20eacb)

**Comment by daniel-jonathan** [comment]
@juanpmarin  Thank you. I appreciate that.

I added all the themes that are currently on the website. You can find them [here](https://github.com/CosmicMind/materialcss/tree/release/src/themes).
